import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import Header from './components/Header';
import { AuthContextProvider } from './context/AuthContext';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Header />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
